backend:
  name: git-gateway
  branch: main
  local_backend: true

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "objects"
    label: "Объекты недвижимости"
    files:
      - file: "data/objects.json"
        label: "Список объектов"
        name: "objects-list"
        fields:
          - label: "Объекты"
            name: "objects"
            widget: list
            fields:
              - { label: "ID", name: "id", widget: "number" }
              - { label: "Заголовок", name: "title", widget: "string" }
              - label: "Статус"
                name: "status"
                widget: "select"
                options:
                  - { label: "Оренда", value: "rent" }
                  - { label: "Продажа", value: "sale" }
                  - { label: "Сдано", value: "rented" }
                  - { label: "Продано", value: "sold" }
              - label: "Тип"
                name: "type"
                widget: "select"
                options:
                  - { label: "Будинок", value: "house" }
                  - { label: "Квартира", value: "apartment" }
                  - { label: "Комерційна", value: "commercial" }
              - { label: "Ціна", name: "price", widget: "string" }
              - label: "Фото"
                name: "images"
                widget: list
                field:
                  { label: "Зображення", name: "url", widget: "image" }
