backend:
  name: git-gateway
  branch: main
  local_backend: true

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "status_options"
    label: "Статусы недвижимости"
    files:
      - file: "data/status_options.yml"
        label: "Статусы"
        name: "status_options"
        fields:
          - label: "Статусы"
            name: "options"
            widget: list
            fields:
              - { label: "Название", name: "label", widget: "string" }
              - { label: "Значение", name: "value", widget: "string" }

  - name: "type_options"
    label: "Типы недвижимости"
    files:
      - file: "data/type_options.yml"
        label: "Типы"
        name: "type_options"
        fields:
          - label: "Типы"
            name: "options"
            widget: list
            fields:
              - { label: "Название", name: "label", widget: "string" }
              - { label: "Значение", name: "value", widget: "string" }

  - name: "objects"
    label: "Объекты недвижимости"
    folder: "data/objects"
    create: true
    slug: "{{id}}"
    extension: "yml"
    format: "yaml"
    fields:
      - { label: "ID", name: "id", widget: "number", required: true }
      - { label: "Заголовок", name: "title", widget: "string", required: true }
      - label: "Статус"
        name: "status"
        widget: "relation"
        collection: "status_options"
        file: "data/status_options.yml"
        search_fields: ["options.label"]
        value_field: "options.value"
        display_fields: ["options.label"]
        required: true
      - label: "Тип"
        name: "type"
        widget: "relation"
        collection: "type_options"
        file: "data/type_options.yml"
        search_fields: ["options.label"]
        value_field: "options.value"
        display_fields: ["options.label"]
        required: true
      - { label: "Цена", name: "price", widget: "number", required: true, min: 0 }
      - label: "Фото (список)"
        name: "images"
        widget: list
        field:
          label: "Фото"
          name: ""
          widget: image
